coordinates:
  bottom_left_corner: [605, 91]
  bottom_right_corner: [593, 406]
  center_left: [384, 173]
  center_right: [384, 173]
  defense_left: [384, 173]
  defense_right: [384, 173]
  goal_left: [384, 173]
  goal_right: [384, 173]
  offense_left: [384, 173]
  offense_right: [384, 173]
  top_left_corner: [40, 78]
  top_right_corner: [39, 393]
